### ISSUE TITLE
Add link to docs and experiments

### ISSUE THREAD

**Issue by animesh-garg** [smpl-env/smpl#1]
The URL to the documentation of smpl: https://smpl-env.github.io/smpl-document/index.html
The URL to the smpl experiments: https://github.com/smpl-env/smpl-experiments

**Comment by marcowus** [comment]
--------------------------------------------------------------------------
RemoteDisconnected                        Traceback (most recent call last)
File ~/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:715, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    714 # Make the request on the httplib connection object.
--> 715 httplib_response = self._make_request(
    716     conn,
    717     method,
    718     url,
    719     timeout=timeout_obj,
    720     body=body,
    721     headers=headers,
    722     chunked=chunked,
    723 )
    725 # If we're going to release the connection in ``finally:``, then
    726 # the response doesn't need to know about the connection. Otherwise
    727 # it will also try to release it and we'll have a double-release
    728 # mess.

File ~/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:467, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    463         except BaseException as e:
    464             # Remove the TypeError from the exception chain in
    465             # Python 3 (including for exceptions like SystemExit).
    466             # Otherwise it looks like a bug in the code.
--> 467             six.raise_from(e, None)
    468 except (SocketTimeout, BaseSSLError, SocketError) as e:

File <string>:3, in raise_from(value, from_value)

File ~/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:462, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    461 try:
--> 462     httplib_response = conn.getresponse()
    463 except BaseException as e:
    464     # Remove the TypeError from the exception chain in
    465     # Python 3 (including for exceptions like SystemExit).
    466     # Otherwise it looks like a bug in the code.

File ~/miniconda3/lib/python3.8/http/client.py:1344, in HTTPConnection.getresponse(self)
   1343 try:
-> 1344     response.begin()
   1345 except ConnectionError:

File ~/miniconda3/lib/python3.8/http/client.py:307, in HTTPResponse.begin(self)
    306 while True:
--> 307     version, status, reason = self._read_status()
    308     if status != CONTINUE:

File ~/miniconda3/lib/python3.8/http/client.py:276, in HTTPResponse._read_status(self)
    273 if not line:
    274     # Presumably, the server closed the connection before
    275     # sending a valid response.
--> 276     raise RemoteDisconnected("Remote end closed connection without"
    277                              " response")
    278 try:

RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
File ~/miniconda3/lib/python3.8/site-packages/requests/adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    488 if not chunked:
--> 489     resp = conn.urlopen(
    490         method=request.method,
    491         url=url,
    492         body=request.body,
    493         headers=request.headers,
    494         redirect=False,
    495         assert_same_host=False,
    496         preload_content=False,
    497         decode_content=False,
    498         retries=self.max_retries,
    499         timeout=timeout,
    500     )
    502 # Send the request.
    503 else:

File ~/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:799, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    797     e = ProtocolError("Connection aborted.", e)
--> 799 retries = retries.increment(
    800     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    801 )
    802 retries.sleep()

File ~/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py:550, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    549 if read is False or not self._is_method_retryable(method):
--> 550     raise six.reraise(type(error), error, _stacktrace)
    551 elif read is not None:

File ~/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py:769, in reraise(tp, value, tb)
    768 if value.__traceback__ is not tb:
--> 769     raise value.with_traceback(tb)
    770 raise value

File ~/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:715, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    714 # Make the request on the httplib connection object.
--> 715 httplib_response = self._make_request(
    716     conn,
    717     method,
    718     url,
    719     timeout=timeout_obj,
    720     body=body,
    721     headers=headers,
    722     chunked=chunked,
    723 )
    725 # If we're going to release the connection in ``finally:``, then
    726 # the response doesn't need to know about the connection. Otherwise
    727 # it will also try to release it and we'll have a double-release
    728 # mess.

File ~/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:467, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    463         except BaseException as e:
    464             # Remove the TypeError from the exception chain in
    465             # Python 3 (including for exceptions like SystemExit).
    466             # Otherwise it looks like a bug in the code.
--> 467             six.raise_from(e, None)
    468 except (SocketTimeout, BaseSSLError, SocketError) as e:

File <string>:3, in raise_from(value, from_value)

File ~/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:462, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    461 try:
--> 462     httplib_response = conn.getresponse()
    463 except BaseException as e:
    464     # Remove the TypeError from the exception chain in
    465     # Python 3 (including for exceptions like SystemExit).
    466     # Otherwise it looks like a bug in the code.

File ~/miniconda3/lib/python3.8/http/client.py:1344, in HTTPConnection.getresponse(self)
   1343 try:
-> 1344     response.begin()
   1345 except ConnectionError:

File ~/miniconda3/lib/python3.8/http/client.py:307, in HTTPResponse.begin(self)
    306 while True:
--> 307     version, status, reason = self._read_status()
    308     if status != CONTINUE:

File ~/miniconda3/lib/python3.8/http/client.py:276, in HTTPResponse._read_status(self)
    273 if not line:
    274     # Presumably, the server closed the connection before
    275     # sending a valid response.
--> 276     raise RemoteDisconnected("Remote end closed connection without"
    277                              " response")
    278 try:

ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
Cell In[10], line 3
      1 import numpy as np
      2 from smpl.envs.atropineenv import AtropineEnvGym
----> 3 env = AtropineEnvGym(normalize=False)
      4 init_state = env.sample_initial_state(no_sample=True)
      5 env.reset(initial_state=init_state)

File ~/smpl-main/smpl/envs/atropineenv.py:179, in AtropineEnvGym.__init__(self, dense_reward, normalize, debug_mode, action_dim, reward_function, done_calculator, observation_name, action_name, np_dtype, max_steps, error_reward, x0_loc, z0_loc, model_loc, uss_subtracted, reward_on_ess_subtracted, reward_on_steady, reward_on_absolute_efactor, reward_on_actions_penalty, reward_on_reject_actions, reward_scaler, relaxed_max_min_actions, observation_include_t, observation_include_action, observation_include_uss, observation_include_ess, observation_include_e, observation_include_kf, observation_include_z, observation_include_x)
    177 else:
    178     raise Exception("z0_loc must be a string, list or a numpy array")
--> 179 response = requests.get(model_loc)
    180 response.raise_for_status()
    181 self.model_preconfig = np.load(io.BytesIO(response.content), allow_pickle=True)

File ~/miniconda3/lib/python3.8/site-packages/requests/api.py:73, in get(url, params, **kwargs)
     62 def get(url, params=None, **kwargs):
     63     r"""Sends a GET request.
     64 
     65     :param url: URL for the new :class:`Request` object.
   (...)
     70     :rtype: requests.Response
     71     """
---> 73     return request("get", url, params=params, **kwargs)

File ~/miniconda3/lib/python3.8/site-packages/requests/api.py:59, in request(method, url, **kwargs)
     55 # By using the 'with' statement we are sure the session is closed, thus we
     56 # avoid leaving sockets open which can trigger a ResourceWarning in some
     57 # cases, and look like a memory leak in others.
     58 with sessions.Session() as session:
---> 59     return session.request(method=method, url=url, **kwargs)

File ~/miniconda3/lib/python3.8/site-packages/requests/sessions.py:587, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    582 send_kwargs = {
    583     "timeout": timeout,
    584     "allow_redirects": allow_redirects,
    585 }
    586 send_kwargs.update(settings)
--> 587 resp = self.send(prep, **send_kwargs)
    589 return resp

File ~/miniconda3/lib/python3.8/site-packages/requests/sessions.py:723, in Session.send(self, request, **kwargs)
    720 if allow_redirects:
    721     # Redirect resolving generator.
    722     gen = self.resolve_redirects(r, request, **kwargs)
--> 723     history = [resp for resp in gen]
    724 else:
    725     history = []

File ~/miniconda3/lib/python3.8/site-packages/requests/sessions.py:723, in <listcomp>(.0)
    720 if allow_redirects:
    721     # Redirect resolving generator.
    722     gen = self.resolve_redirects(r, request, **kwargs)
--> 723     history = [resp for resp in gen]
    724 else:
    725     history = []

File ~/miniconda3/lib/python3.8/site-packages/requests/sessions.py:266, in SessionRedirectMixin.resolve_redirects(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)
    263     yield req
    264 else:
--> 266     resp = self.send(
    267         req,
    268         stream=stream,
    269         timeout=timeout,
    270         verify=verify,
    271         cert=cert,
    272         proxies=proxies,
    273         allow_redirects=False,
    274         **adapter_kwargs,
    275     )
    277     extract_cookies_to_jar(self.cookies, prepared_request, resp.raw)
    279     # extract redirect url, if any, for the next loop

File ~/miniconda3/lib/python3.8/site-packages/requests/sessions.py:701, in Session.send(self, request, **kwargs)
    698 start = preferred_clock()
    700 # Send the request
--> 701 r = adapter.send(request, **kwargs)
    703 # Total elapsed time of the request (approximately)
    704 elapsed = preferred_clock() - start

File ~/miniconda3/lib/python3.8/site-packages/requests/adapters.py:547, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    544             raise
    546 except (ProtocolError, OSError) as err:
--> 547     raise ConnectionError(err, request=request)
    549 except MaxRetryError as e:
    550     if isinstance(e.reason, ConnectTimeoutError):
    551         # TODO: Remove this in 3.0.0: see #2811

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))


I'm facing an issue while trying to initialize the AtropineEnvGym environment from the smpl library. This error seems to be occurring when the code tries to fetch the model configuration from the specified model_loc URL. The relevant lines of code are:response = requests.get(model_loc)
response.raise_for_status()
self.model_preconfig = np.load(io.BytesIO(response.content), allow_pickle=True)
Could you please help me understand what might be causing this issue? Is there a problem with the URL or the server hosting the model configuration? I'm using the latest version of the smpl library, and I haven't made any modifications to the AtropineEnvGym code.

**Comment by marcowus** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 3
      1 from smpl.envs.mabenv import MAbEnvGym, xscale, uscale
      2 import numpy as np
----> 3 env = MAbEnvGym(normalize=False, standard_reward_style='setpoint')
      4 xss = env.xss / xscale
      5 uss = env.uss / uscale

File ~/smpl-main/smpl/envs/mabenv.py:182, in MAbEnvGym.__init__(self, dataset_dir, dense_reward, normalize, debug_mode, action_dim, observation_dim, reward_function, done_calculator, max_observations, min_observations, max_actions, min_actions, observation_name, action_name, np_dtype, max_steps, error_reward, initial_state_deviation_ratio, upstream_states, switch_threshold, dt_itgr, dt_spl, ss_dir, standard_reward_style)
    179 self.min_actions, self.max_actions, self.min_observations, self.max_observations = self.min_actions / uscale, self.max_actions / uscale, self.min_observations / xscale, self.max_observations / xscale
    180 self.controller = ControllerHelper(self.num_x, self.num_u, self.max_steps, dt_itgr, dt_spl, xscale, uscale,
    181                                    self.xss, self.uss)
--> 182 self.plant = self.controller._build_plant()
    184 # define the state and action spaces
    185 self.max_observations = np.array(self.max_observations, dtype=self.np_dtype)

File ~/smpl-main/smpl/envs/helpers/mab_helpers.py:86, in ControllerHelper._build_plant(self)
     84 def _build_plant(self):
     85     xdot_scale = self.model_helper.xdot_scale  # Excluding the time information
---> 86     self.plant = mpc.DiscreteSimulator(xdot_scale, self.dt_itgl, [self.Nx, self.Nu], ['x', 'u'])
     87     return self.plant

AttributeError: module 'mpctools' has no attribute 'DiscreteSimulator'


Could you please let me know which version of mpctools you used while developing the smpl library? How should I correctly install the version of mpctools that includes the DiscreteSimulator? Or is there any other solution that would allow me to run the MAbEnvGym environment smoothly?

**Comment by Mohan-Zhang-u** [comment]
Hi @marcowus , please use this one: https://github.com/cknoll/mpctools_casadi
